### ISSUE TITLE
Download the ThreadX repo, could not get the requirment branch

### ISSUE THREAD

**Issue by Huazi715** [eclipse-threadx/threadx#417]
Hi,
git clone the thread core code.  But there are not the v6.1.3 branch.

How can I get the correct branch 6.1.3? 

![image](https://github.com/user-attachments/assets/c41b63d5-ec9a-4120-8017-6ccbc77cd363)
![image-1](https://github.com/user-attachments/assets/db44733f-3d53-478b-bbc3-c7aa870eeec6)

**Comment by fdesbiens** [comment]
Hi @Huazi715.

Releases for ThreadX and its modules are tagged; they do not have their own branch after release.

For your convenience, here are the tags for the latest certified components.

| Component name | Version | GitHub Tag |
| -------------- | ------- | ---------- |
| ThreadX | 6.1.1 | https://github.com/eclipse-threadx/threadx/releases/tag/v6.1.1_rel |
| ThreadX SMP | 6.1.3 | https://github.com/eclipse-threadx/threadx/releases/tag/v6.1.3_rel |
| GUIX | 6.1.7 | https://github.com/eclipse-threadx/guix/releases/tag/v6.1.7_rel |
| NetX Duo | 6.1.9 | https://github.com/eclipse-threadx/netxduo/releases/tag/v6.1.9_rel |
| USBX | 6.1.11 | https://github.com/eclipse-threadx/usbx/releases/tag/v6.1.11_rel |

Please note that ThreadX and ThreadX SMP are in the same GitHub repository, but their certified versions differ.

I hope this helps. Let me know if you have other questions; otherwise, I will close this issue.

**Comment by Huazi715** [comment]
Hi Frédéric Desbiens,




Yeah, I know this way, but this download method is the zip or tar.gz format, I could check merge log by the cmd git log.

Is there other download method that can check merge log？




BR/Hua




At 2024-11-12 11:40:19, "Frédéric Desbiens" ***@***.***> wrote:

Hi @Huazi715.

Releases for ThreadX and its modules are tagged; they do not have their own branch after release.

For your convenience, here are the tags for the latest certified components.

| Component name | Version | GitHub Tag |
| ThreadX | 6.1.1 | https://github.com/eclipse-threadx/threadx/releases/tag/v6.1.1_rel |
| ThreadX SMP | 6.1.3 | https://github.com/eclipse-threadx/threadx/releases/tag/v6.1.3_rel |
| GUIX | 6.1.7 | https://github.com/eclipse-threadx/guix/releases/tag/v6.1.7_rel |
| NetX Duo | 6.1.9 | https://github.com/eclipse-threadx/netxduo/releases/tag/v6.1.9_rel |
| USBX | 6.1.11 | https://github.com/eclipse-threadx/usbx/releases/tag/v6.1.11_rel |

Please note that ThreadX and ThreadX SMP are in the same GitHub repository, but their certified versions differ.

I hope this helps. Let me know if you have other questions; otherwise, I will close this issue.

**Comment by fdesbiens** [comment]
Hi Hua.

You can checkout any tag in a branch. For example, if you wanted to checkout ThreadX 6.1.3 (tag `v6.1.3_rel`) and create a local branch named `dev` to work on the code, you would issue the following command:

```
git checkout -b dev tags/v6.1.3_rel
```

**Comment by Huazi715** [comment]
Yeah,  got it. Thank you.
I will close this issue.
